question_data = [
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "The Republic of Malta is the smallest microstate worldwide.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
     "difficulty": "easy",
     "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "easy",
     "question": "The anime Lucky Star follows the story of one girl who is unaware she is God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "Denmark has a monarch.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Pluto is a planet.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A flock of crows is known as a homicide.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A pasodoble is a type of Italian pasta sauce.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]
